version: '3.9'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:16
    container_name: furniture_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5666:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO Object Storage Service
  minio:
    image: minio/minio:latest
    container_name: furniture_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # MinIO API Port
      - "9001:9001" # MinIO Console UI Port
    volumes:
      - minio_data:/data

  # Redis Service
  redis:
    image: redis:7
    container_name: furniture_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  # Elysia API Service
  # api:
  #   build: .
  #   container_name: furniture_api
  #   restart: always
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     db:
  #       condition: service_healthy # รอให้ db พร้อมใช้งานก่อน
  #     minio:
  #       condition: service_started
  #     redis:
  #       condition: service_started
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app

volumes:
  postgres_data:
  redis_data:
  minio_data: